export const episodeArray = [
  {
    episodeCount: 1,
    episodeNumber: 1,
    title: "Ambush",
    quote: "Great leaders inspire greatness in others",
    season: 1,
  },
  {
    episodeCount: 2,
    episodeNumber: 2,
    title: "Rising Malevolence",
    quote: "Belief is not a matter of choice, but of conviction",
    season: 1,
  },
  {
    episodeCount: 3,
    episodeNumber: 3,
    title: "Shadow of Malevolence",
    quote: "Easy is the path to wisdom for those not blinded by ego",
    season: 1,
  },
  {
    episodeCount: 4,
    episodeNumber: 4,
    title: "Destroy Malevolence",
    quote: "A plan is only as good as those who see it through",
    season: 1,
  },
  {
    episodeCount: 5,
    episodeNumber: 5,
    title: "Rookies",
    quote: "The best confidence builder is experience",
    season: 1,
  },
  {
    episodeCount: 6,
    episodeNumber: 6,
    title: "Downfall of a Droid",
    quote: "Trust in your friends, and they’ll have reason to trust in you",
    season: 1,
  },
  {
    episodeCount: 7,
    episodeNumber: 7,
    title: "Duel of the Droids",
    quote:
      "You hold onto friends by keeping your heart a little softer than your head",
    season: 1,
  },
  {
    episodeCount: 8,
    episodeNumber: 8,
    title: "Bombad Jedi",
    quote: "Heroes are made by the times",
    season: 1,
  },
  {
    episodeCount: 9,
    episodeNumber: 9,
    title: "Cloak of Darkness",
    quote: "Ignore your instincts at your peril",
    season: 1,
  },
  {
    episodeCount: 10,
    episodeNumber: 10,
    title: "Lair of Grievous",
    quote: "Most powerful is he who controls his own power",
    season: 1,
  },
  {
    episodeCount: 11,
    episodeNumber: 11,
    title: "Dooku Captured",
    quote:
      "The winding path to peace is always a worthy one, regardless of how many turns it takes",
    season: 1,
  },
  {
    episodeCount: 12,
    episodeNumber: 12,
    title: "The Gungan General",
    quote: "Fail with honor rather than succeed by fraud",
    season: 1,
  },
  {
    episodeCount: 13,
    episodeNumber: 13,
    title: "Jedi Crash",
    quote: "Greed and fear of loss are the roots that lead to the tree of evil",
    season: 1,
  },
  {
    episodeCount: 14,
    episodeNumber: 14,
    title: "Defenders of Peace",
    quote: "When surrounded by war, one must eventually choose a side",
    season: 1,
  },
  {
    episodeCount: 15,
    episodeNumber: 15,
    title: "Trespass",
    quote: "Arrogance diminishes wisdom",
    season: 1,
  },
  {
    episodeCount: 16,
    episodeNumber: 16,
    title: "The Hidden Enemy",
    quote:
      "Truth enlightens the mind, but won’t always bring happiness to your heart",
    season: 1,
  },
  {
    episodeCount: 17,
    episodeNumber: 17,
    title: "Blue Shadow Virus",
    quote: "Fear is a disease; hope is its only cure",
    season: 1,
  },
  {
    episodeCount: 18,
    episodeNumber: 18,
    title: "Mystery of the Thousand Moons",
    quote: "A single chance is a galaxy of hope",
    season: 1,
  },
  {
    episodeCount: 19,
    episodeNumber: 19,
    title: "Storm over Ryloth",
    quote: "It is a rough road that leads to the heights of greatness",
    season: 1,
  },
  {
    episodeCount: 20,
    episodeNumber: 20,
    title: "Innocents of Ryloth",
    quote: "The costs of war can never be truly accounted for",
    season: 1,
  },
  {
    episodeCount: 21,
    episodeNumber: 21,
    title: "Liberty on Ryloth",
    quote:
      "Compromise is a virtue to be cultivated, not a weakness to be despised",
    season: 1,
  },
  {
    episodeCount: 22,
    episodeNumber: 22,
    title: "Hostage Crisis",
    quote: "A secret shared is a trust formed",
    season: 1,
  },
  {
    episodeCount: 23,
    episodeNumber: 1,
    title: "Holocron Heist",
    quote: "A lesson learned is a lesson earned",
    season: 2,
  },
  {
    episodeCount: 24,
    episodeNumber: 2,
    title: "Cargo of Doom",
    quote: "Overconfidence is the most dangerous form of carelessness",
    season: 2,
  },
  {
    episodeCount: 25,
    episodeNumber: 3,
    title: "Children of the Force",
    quote: "The first step to correcting a mistake is patience",
    season: 2,
  },
  {
    episodeCount: 26,
    episodeNumber: 4,
    title: "Senate Spy",
    quote: "A true heart should never be doubted",
    season: 2,
  },
  {
    episodeCount: 27,
    episodeNumber: 5,
    title: "Landing at Point Rain",
    quote: "Believe in yourself or no one else will",
    season: 2,
  },
  {
    episodeCount: 28,
    episodeNumber: 6,
    title: "Weapons Factory",
    quote: "No gift is more precious than trust",
    season: 2,
  },
  {
    episodeCount: 29,
    episodeNumber: 7,
    title: "Legacy of Terror",
    quote: "Sometimes, accepting help is harder than offering it",
    season: 2,
  },
  {
    episodeCount: 30,
    episodeNumber: 8,
    title: "Brain Invaders",
    quote: "Attachment is not compassion",
    season: 2,
  },
  {
    episodeCount: 31,
    episodeNumber: 9,
    title: "Grievous Intrigue",
    quote: "For everything you gain, you lose something else",
    season: 2,
  },
  {
    episodeCount: 32,
    episodeNumber: 10,
    title: "The Deserter",
    quote: "It is the quest for honor that makes one honorable",
    season: 2,
  },
  {
    episodeCount: 33,
    episodeNumber: 11,
    title: "Lightsaber Lost",
    quote: "Easy isn’t always simple",
    season: 2,
  },
  {
    episodeCount: 34,
    episodeNumber: 12,
    title: "The Mandalore Plot",
    quote: "If you ignore the past, you jeopardize the future",
    season: 2,
  },
  {
    episodeCount: 35,
    episodeNumber: 13,
    title: "Voyage of Temptation",
    quote: "Fear not for the future, weep not for the past",
    season: 2,
  },
  {
    episodeCount: 36,
    episodeNumber: 14,
    title: "Duchess of Mandalore",
    quote: "In war, truth is the first casualty",
    season: 2,
  },
  {
    episodeCount: 37,
    episodeNumber: 15,
    title: "Senate Murders",
    quote: "Searching for the truth is easy",
    season: 2,
  },
  {
    episodeCount: 38,
    episodeNumber: 16,
    title: "Cat and Mouse",
    quote: "A wise leader knows when to follow",
    season: 2,
  },
  {
    episodeCount: 39,
    episodeNumber: 17,
    title: "Bounty Hunters",
    quote: "Courage makes heroes, but trust builds friendships",
    season: 2,
  },
  {
    episodeCount: 40,
    episodeNumber: 18,
    title: "The Zillo Beast",
    quote: "Choose what is right, not what is easy",
    season: 2,
  },
  {
    episodeCount: 41,
    episodeNumber: 19,
    title: "The Zillo Beast Strikes Back",
    quote: "The most dangerous beast is the beast within",
    season: 2,
  },
  {
    episodeCount: 42,
    episodeNumber: 20,
    title: "Death Trap",
    quote: "Who my father was matters less than my memory of him",
    season: 2,
  },
  {
    episodeCount: 43,
    episodeNumber: 21,
    title: "R2 Come Home",
    quote: "Adversity is a friendship’s truest test",
    season: 2,
  },
  {
    episodeCount: 44,
    episodeNumber: 22,
    title: "Lethal Trackdown",
    quote: "Revenge is a confession of pain",
    season: 2,
  },
  {
    episodeCount: 45,
    episodeNumber: 1,
    title: "Clone Cadets",
    quote: "Brothers in arms are brothers for life",
    season: 3,
  },
  {
    episodeCount: 46,
    episodeNumber: 2,
    title: "ARC Troopers",
    quote:
      "Fighting a war tests a soldier’s skills, defending his home tests a soldier’s heart",
    season: 3,
  },
  {
    episodeCount: 47,
    episodeNumber: 3,
    title: "Supply Lines",
    quote: "Where there’s a will, there’s a way",
    season: 3,
  },
  {
    episodeCount: 48,
    episodeNumber: 4,
    title: "Sphere of Influence",
    quote: "A child stolen is a hope lost",
    season: 3,
  },
  {
    episodeCount: 49,
    episodeNumber: 5,
    title: "Corruption",
    quote: "The challenge of hope is to overcome corruption",
    season: 3,
  },
  {
    episodeCount: 50,
    episodeNumber: 6,
    title: "The Academy",
    quote: "Those who enforce the law must obey the law",
    season: 3,
  },
  {
    episodeCount: 51,
    episodeNumber: 7,
    title: "Assassin",
    quote: "The future has many paths – choose wisely",
    season: 3,
  },
  {
    episodeCount: 52,
    episodeNumber: 8,
    title: "Evil Plans",
    quote: "A failure in planning is a plan for failure",
    season: 3,
  },
  {
    episodeCount: 53,
    episodeNumber: 9,
    title: "Hunt for Ziro",
    quote: "Love comes in all shapes and sizes",
    season: 3,
  },
  {
    episodeCount: 54,
    episodeNumber: 10,
    title: "Heroes on Both Sides",
    quote: "Fear is a great motivator",
    season: 3,
  },
  {
    episodeCount: 55,
    episodeNumber: 11,
    title: "Pursuit of Peace",
    quote: "Truth can strike down the spectre of fear",
    season: 3,
  },
  {
    episodeCount: 56,
    episodeNumber: 12,
    title: "Nightsisters",
    quote: "The swiftest path to destruction is through vengeance",
    season: 3,
  },
  {
    episodeCount: 57,
    episodeNumber: 13,
    title: "Monster",
    quote: "Evil is not born, it is taught",
    season: 3,
  },
  {
    episodeCount: 58,
    episodeNumber: 14,
    title: "Witches of the Mist",
    quote: "The path to evil may bring great power, but not loyalty",
    season: 3,
  },
  {
    episodeCount: 59,
    episodeNumber: 15,
    title: "Overlords",
    quote: "Balance is found in the one who faces his guilt",
    season: 3,
  },
  {
    episodeCount: 60,
    episodeNumber: 16,
    title: "Altar of Mortis",
    quote: "He who surrenders hope, surrenders life",
    season: 3,
  },
  {
    episodeCount: 61,
    episodeNumber: 17,
    title: "Ghosts of Mortis",
    quote: "He who seeks to control fate shall never find peace",
    season: 3,
  },
  {
    episodeCount: 62,
    episodeNumber: 18,
    title: "The Citadel",
    quote: "Adaptation is the key to survival",
    season: 3,
  },
  {
    episodeCount: 63,
    episodeNumber: 19,
    title: "Counterattack",
    quote: "Anything that can go wrong will",
    season: 3,
  },
  {
    episodeCount: 64,
    episodeNumber: 20,
    title: "Citadel Rescue",
    quote: "Without honor, victory is hollow",
    season: 3,
  },
  {
    episodeCount: 65,
    episodeNumber: 21,
    title: "Padawan Lost",
    quote: "Without humility, courage is a dangerous game",
    season: 3,
  },
  {
    episodeCount: 66,
    episodeNumber: 22,
    title: "Wookie Hunt",
    quote: "A great student is what the teacher hopes to be",
    season: 3,
  },
  {
    episodeCount: 67,
    episodeNumber: 1,
    title: "Water War",
    quote: "When destiny calls, the chosen have no choice",
    season: 4,
  },
  {
    episodeCount: 68,
    episodeNumber: 2,
    title: "Gungan Attack",
    quote: "Only through fire is a strong sword forged",
    season: 4,
  },
  {
    episodeCount: 69,
    episodeNumber: 3,
    title: "Prisoners",
    quote: "Crowns are inherited, kingdoms are earned",
    season: 4,
  },
  {
    episodeCount: 70,
    episodeNumber: 4,
    title: "Shadow Warrior",
    quote: "Who a person truly is cannot be seen with the eye",
    season: 4,
  },
  {
    episodeCount: 71,
    episodeNumber: 5,
    title: "Mercy Mission",
    quote: "Understanding is honoring the truth beneath the surface",
    season: 4,
  },
  {
    episodeCount: 72,
    episodeNumber: 6,
    title: "Nomad Droids",
    quote:
      "Who’s the more foolish, the fool or the fool who follows him? 04×07 – Darkness on Umbara: The first step towards loyalty is trust",
    season: 4,
  },
  {
    episodeCount: 73,
    episodeNumber: 8,
    title: "The General",
    quote: "The path of ignorance is guided by fear",
    season: 4,
  },
  {
    episodeCount: 74,
    episodeNumber: 9,
    title: "Plan of Dissent",
    quote: "The wise man leads, the strong man follows",
    season: 4,
  },
  {
    episodeCount: 75,
    episodeNumber: 10,
    title: "Carnage of Krell",
    quote: "Our actions define our legacy",
    season: 4,
  },
  {
    episodeCount: 76,
    episodeNumber: 11,
    title: "Kidnapped",
    quote: "Where we are going always reflects where we came from",
    season: 4,
  },
  {
    episodeCount: 77,
    episodeNumber: 12,
    title: "Slaves of the Republic",
    quote: "Those who enslave others, inevitably become slaves themselves",
    season: 4,
  },
  {
    episodeCount: 78,
    episodeNumber: 13,
    title: "Escape from Kadavo",
    quote: "Great hope can come from small sacrifices",
    season: 4,
  },
  {
    episodeCount: 79,
    episodeNumber: 14,
    title: "A Friend in Need",
    quote: "Friendship shows us who we really are",
    season: 4,
  },
  {
    episodeCount: 80,
    episodeNumber: 15,
    title: "Deception",
    quote: "All warfare is based on deception",
    season: 4,
  },
  {
    episodeCount: 81,
    episodeNumber: 16,
    title: "Friends and Enemies",
    quote: "Keep your friends close, but keep your enemies closer",
    season: 4,
  },
  {
    episodeCount: 82,
    episodeNumber: 17,
    title: "The Box",
    quote: "The strong survive, the noble overcome",
    season: 4,
  },
  {
    episodeCount: 83,
    episodeNumber: 18,
    title: "Crisis on Naboo",
    quote: "Trust is the greatest of gifts, but it must be earned",
    season: 4,
  },
  {
    episodeCount: 84,
    episodeNumber: 19,
    title: "Massacre",
    quote: "One must let go of the past to hold on to the future",
    season: 4,
  },
  {
    episodeCount: 85,
    episodeNumber: 20,
    title: "Bounty",
    quote: "Who we are never changes, who we think we are does",
    season: 4,
  },
  {
    episodeCount: 86,
    episodeNumber: 21,
    title: "Brothers",
    quote:
      "A fallen enemy may rise again, but the reconciled one is truly vanquished",
    season: 4,
  },
  {
    episodeCount: 87,
    episodeNumber: 22,
    title: "Revenge",
    quote: "The enemy of my enemy is my friend",
    season: 4,
  },
  {
    episodeCount: 88,
    episodeNumber: 1,
    title: "Revival",
    quote: "Strength of character can defeat strength in numbers",
    season: 5,
  },
  {
    episodeCount: 89,
    episodeNumber: 2,
    title: "A War on Two Fronts",
    quote: "Fear is a malleable weapon",
    season: 5,
  },
  {
    episodeCount: 90,
    episodeNumber: 3,
    title: "Front Runners",
    quote: "To seek something is to believe in its possibility",
    season: 5,
  },
  {
    episodeCount: 91,
    episodeNumber: 4,
    title: "The Soft War",
    quote: "Struggles often begin and end with the truth",
    season: 5,
  },
  {
    episodeCount: 92,
    episodeNumber: 5,
    title: "Tipping Points",
    quote: "Disobedience is a demand for change",
    season: 5,
  },
  {
    episodeCount: 93,
    episodeNumber: 6,
    title: "The Gathering",
    quote: "He who faces himself, finds himself",
    season: 5,
  },
  {
    episodeCount: 94,
    episodeNumber: 7,
    title: "A Test of Strength",
    quote: "The young are often underestimated",
    season: 5,
  },
  {
    episodeCount: 95,
    episodeNumber: 8,
    title: "Bound for Rescue",
    quote: "When we rescue others, we rescue ourselves",
    season: 5,
  },
  {
    episodeCount: 96,
    episodeNumber: 9,
    title: "A Necessary Bond",
    quote: "Choose your enemies wisely, as they may be your last hope",
    season: 5,
  },
  {
    episodeCount: 97,
    episodeNumber: 10,
    title: "Secret Weapons",
    quote: "Humility is the only defense against humiliation",
    season: 5,
  },
  {
    episodeCount: 98,
    episodeNumber: 11,
    title: "A Sunny Day in the Void",
    quote: "When all seems hopeless, a true hero gives hope",
    season: 5,
  },
  {
    episodeCount: 99,
    episodeNumber: 12,
    title: "Missing in Action",
    quote: "A soldier’s most powerful weapon is courage",
    season: 5,
  },
  {
    episodeCount: 100,
    episodeNumber: 13,
    title: "Point of No Return",
    quote: "You must trust in others or success is impossible",
    season: 5,
  },
  {
    episodeCount: 101,
    episodeNumber: 14,
    title: "Eminence",
    quote: "One vision can have many interpretations",
    season: 5,
  },
  {
    episodeCount: 102,
    episodeNumber: 15,
    title: "Shades of Reason",
    quote: "Alliances can stall true intentions",
    season: 5,
  },
  {
    episodeCount: 103,
    episodeNumber: 16,
    title: "The Lawless",
    quote: "Morality separates heroes from villains",
    season: 5,
  },
  {
    episodeCount: 104,
    episodeNumber: 17,
    title: "Sabotage",
    quote: "Sometimes even the smallest doubt can shake the greatest belief",
    season: 5,
  },
  {
    episodeCount: 105,
    episodeNumber: 18,
    title: "The Jedi Who Knew Too Much",
    quote: "Courage begins by trusting oneself",
    season: 5,
  },
  {
    episodeCount: 106,
    episodeNumber: 19,
    title: "To Catch a Jedi",
    quote: "Never become desperate enough to trust the untrustworthy",
    season: 5,
  },
  {
    episodeCount: 107,
    episodeNumber: 20,
    title: "The Wrong Jedi",
    quote: "Never give up hope, no matter how dark things seem",
    season: 5,
  },
  {
    episodeCount: 108,
    episodeNumber: 1,
    title: "The Unknown",
    quote: "The truth about yourself is always the hardest to accept",
    season: 6,
  },
  {
    episodeCount: 109,
    episodeNumber: 2,
    title: "Conspiracy",
    quote: "The wise benefit from a second opinion",
    season: 6,
  },
  {
    episodeCount: 110,
    episodeNumber: 3,
    title: "Fugitive",
    quote: "When in doubt, go to the source",
    season: 6,
  },
  {
    episodeCount: 111,
    episodeNumber: 4,
    title: "Orders",
    quote: "The popular belief isn’t always the correct one",
    season: 6,
  },
  {
    episodeCount: 112,
    episodeNumber: 5,
    title: "An Old Friend",
    quote: "To love, is to trust",
    season: 6,
  },
  {
    episodeCount: 113,
    episodeNumber: 6,
    title: "The Rise of Clovis",
    quote: "Jealousy is the path to chaos",
    season: 6,
  },
  {
    episodeCount: 114,
    episodeNumber: 7,
    title: "Crisis at the Heart",
    quote: "Deceit is the weapon of greed",
    season: 6,
  },
  {
    episodeCount: 115,
    episodeNumber: 8,
    title: "The Disappeared Part 1",
    quote: "Without darkness there cannot be light",
    season: 6,
  },
  {
    episodeCount: 116,
    episodeNumber: 9,
    title: "The Disappeared Part 2",
    quote: "Wisdom is born in fools as well as wise men",
    season: 6,
  },
  {
    episodeCount: 117,
    episodeNumber: 10,
    title: "The Lost One",
    quote: "What is lost is often found",
    season: 6,
  },
  {
    episodeCount: 118,
    episodeNumber: 11,
    title: "Voices",
    quote: "Madness can sometimes be the path to truth",
    season: 6,
  },
  {
    episodeCount: 119,
    episodeNumber: 12,
    title: "Destiny",
    quote: "Death is just the beginning",
    season: 6,
  },
  {
    episodeCount: 120,
    episodeNumber: 13,
    title: "Sacrifice",
    quote: "Facing all that you fear will free you from yourself",
    season: 6,
  },
  {
    episodeCount: 121,
    episodeNumber: 1,
    title: "The Bad Batch",
    quote: "Embrace others for their differences, for that makes you whole",
    season: 7,
  },
  {
    episodeCount: 122,
    episodeNumber: 2,
    title: "A Distant Echo",
    quote: "The search for truth begins with belief",
    season: 7,
  },
  {
    episodeCount: 123,
    episodeNumber: 3,
    title: "On the Wings of Keeradaks",
    quote: "Survival is one step on the path to living",
    season: 7,
  },
  {
    episodeCount: 124,
    episodeNumber: 4,
    title: "Unfinished Business",
    quote: "Trust placed in another is trust earned",
    season: 7,
  },
  {
    episodeCount: 125,
    episodeNumber: 5,
    title: "Gone with a Trace",
    quote: "If there is no path before you, create your own",
    season: 7,
  },
  {
    episodeCount: 126,
    episodeNumber: 6,
    title: "Deal No Deal",
    quote: "Mistakes are valuable lessons often learned too late",
    season: 7,
  },
  {
    episodeCount: 127,
    episodeNumber: 7,
    title: "Dangerous Debt",
    quote: "Who you were does not have to define who you are",
    season: 7,
  },
  {
    episodeCount: 128,
    episodeNumber: 8,
    title: "Together Again",
    quote: "You can change who you are, but you cannot run from yourself",
    season: 7,
  },
  {
    episodeCount: 129,
    episodeNumber: 9,
    title: "Old Friends Not Forgotten",
    quote: "No opening quote",
    season: 7,
  },
  {
    episodeCount: 130,
    episodeNumber: 10,
    title: "Phantom Apprentice",
    quote: "No opening quote",
    season: 7,
  },
  {
    episodeCount: 131,
    episodeNumber: 11,
    title: "Shattered",
    quote: "No opening quote",
    season: 7,
  },
  {
    episodeCount: 132,
    episodeNumber: 12,
    title: "Victory and Death",
    quote: "No opening quote",
    season: 7,
  },
];
